name = "backend"
compatibility_date = "2025-12-01"

[vars]
DATABASE_URL="prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19TWGRvY3lxaVE3a0dKSGhEcTVBTFMiLCJhcGlfa2V5IjoiMDFLN0s0N0pCRzRXR0FOWjQ3UUYxMzczQlAiLCJ0ZW5hbnRfaWQiOiJiYjQ0ZWM1NWQ4ZDE3ODk2NGZiYTYwODhiOGFkOWU3ZjI4M2Q0MjkzOTVmOTM2ZWEyMmM0ZWY1ODdkMWVmZmU2IiwiaW50ZXJuYWxfc2VjcmV0IjoiNWI5NzM1MDUtNDExOS00MmRmLWJkMDktYmM1NWIwNGUzNGMyIn0.aR8ILDtUlRO8-DoKKNliWlnrLai-KvpSMUYhrAmMn6c"
JWT_SECRET="Rishabh1234"