name = "backend"
compatibility_date = "2025-10-15"

[vars]

DATABASE_URL="prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19DOG1DT0w4andvMDhlMmw4TFlqNF8iLCJhcGlfa2V5IjoiMDFLN000MjkyVkNRNjhLUEtCTkg4Nzg1Tk0iLCJ0ZW5hbnRfaWQiOiJiYjQ0ZWM1NWQ4ZDE3ODk2NGZiYTYwODhiOGFkOWU3ZjI4M2Q0MjkzOTVmOTM2ZWEyMmM0ZWY1ODdkMWVmZmU2IiwiaW50ZXJuYWxfc2VjcmV0IjoiNWI5NzM1MDUtNDExOS00MmRmLWJkMDktYmM1NWIwNGUzNGMyIn0.EPpl3APkvsb_69J4jYBgk6gfyIdKAdzOm8PjPsjvNFg"